### ISSUE TITLE
Seeder crashes while generating images.

### ISSUE THREAD

**Issue by SoetZombie** [Ucommercenet/Ucommerce-Seeder#14]
Using seeder on umbraco 8.2.1 results in following error: 

```
Generating 10 media folders with 100 images in each. 4 secs
Unhandled Exception: System.Exception: Oops! A `GUID` has been provided, but the property: 'UniqueId' is currently specified to be database gene
rated. Is it intended? Please report the issue to our support team if you believe this error should not appear: info@zzzprojects.com
   at ?.?`1.?(? ?)
   at ?.Read()
   at ?.?()
   at System.Data.SqlClient.SqlBulkCopy.ReadFromRowSourceAsync(CancellationToken cts)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at ?.?(? ?, DbConnection ?, DbTransaction ?, Int32 ?)
   at ?.?(? ?)
   at ?.Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Ucommerce.Seeder.DataSeeding.Tasks.Cms.UmbracoMediaSeedingTask.Seed(UmbracoDbContext context) in C:\repos\Ucommerce-Seeder\src\DataSeeding
\Tasks\Cms\UmbracoMediaSeedingTask.cs:line 97
   at Ucommerce.Seeder.DataSeeding.DataSeeder.Seed(Func`1 dbContextFactory) in C:\repos\Ucommerce-Seeder\src\DataSeeding\DataSeeder.cs:line 77
   at Ucommerce.Seeder.Seeder.Run() in C:\repos\Ucommerce-Seeder\src\Seeder.cs:line 73
   at Ucommerce.Seeder.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in C:\repos\Ucommerce-Seeder\src\Program.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at Ucommerce.Seeder.Program.Main(String[] args) in C:\repos\Ucommerce-Seeder\src\Program.cs:line 47
```

It seems more like a bug in ZZZ as I believe we want to have both GUID and UniqueID in the DB. ZZZ version 2.93

**Comment by skovsboll** [comment]
It's been almost a year since we abandoned ZZZ. I wonder whether you're on the latest develop @SoetZombie?

**Comment by SoetZombie** [comment]
> It's been almost a year since we abandoned ZZZ. I wonder whether you're on the latest develop @SoetZombie?

I though I was. Will need to check it up again.

**Comment by nebse** [comment]
@SoetZombie did you make any progress on this or can we close?
